### ISSUE TITLE
Execute testcase tcp/blocking/blocking-write.pkt failed

### ISSUE THREAD

**Issue by Bubble-mt** [google/packetdrill#58]
Execute testcase packetdrill/gtests/net/tcp/blocking/blocking-write.pkt  by packetdrill failed, command as below:
../../packetdrill/packetdrill blocking-write.pkt
<img width="502" alt="1632466747(1)" src="https://user-images.githubusercontent.com/72586297/134631845-02594cbf-e145-485e-b82b-f509251140b6.png">

The temp file didn't remove.
<img width="306" alt="1632466778(1)" src="https://user-images.githubusercontent.com/72586297/134631924-3c5554bc-9473-4cc6-89dc-9fa6efe3fa9e.png">

**Comment by nealcardwell** [comment]
Hi,

It looks like perhaps in your copy of blocking-write.pkt you have removed
the line:

../common/set_sysctls.py /proc/sys/net/ipv4/tcp_min_tso_segs=10


Is that so?

If that is not the issue, then can you please share the output of the
following commands, so we can see exactly which version of the scripts you
are using, and what OS distribution and kernel:

git remote -v | grep packetdrill
git log --oneline | head -2
cat /etc/lsb-release
uname -r

Thanks!

neal

**Comment by Bubble-mt** [comment]
Hi Neal,

I didn't remove the line. Below is the verbose output of command.
<img width="668" alt="1632618650(1)" src="https://user-images.githubusercontent.com/72586297/134789741-acb9f0c0-8640-4a37-a905-ce9fc36cae0a.png">

Below are git version, OS distribution and kernel:
<img width="504" alt="1632618749(1)" src="https://user-images.githubusercontent.com/72586297/134789768-77c40ddb-3ca0-4187-97e2-12b9e7dfd915.png">


BTW, I found if I add a blank link.
`../common/defaults.sh
 ../common/set_sysctls.py /proc/sys/net/ipv4/tcp_min_tso_segs=10

`
I could execute the script succeed.
<img width="674" alt="580cd8cb419784929e9bc9cb2dcfb68" src="https://user-images.githubusercontent.com/72586297/134789851-df8ccd30-3f32-463a-9275-40c03f14203a.png">

**Comment by nealcardwell** [comment]
The  blocking-write.pkt script works for me as-is with an Ubuntu 20.04
machine with a kernel based on v5.13.12. I'm not sure why it's not working
in your environment. If you are able to find a root cause, please feel free
to submit a patch. Thanks!

neal
