### ISSUE TITLE
Heap-buffer-overflow in ipv4_header_len.

### ISSUE THREAD

**Issue by koltiradw** [google/packetdrill#63]
Hi! I found heap-buffer-overflow ( occurs at net/packetdrill/ip.h:99 ) during testing with libFuzzer.
Perhaps to fix the error, you can try to change the code in net/packetdrill/packet_parser.c:211 to 
`
struct ipv4 *ipv4 = (struct ipv4 *) malloc(sizeof(struct ipv4));
`
`
memcpy(ipv4, header_start, sizeof(struct ipv4));
`
- Harness for libfuzzer and crash file: [artifacts.zip](https://github.com/google/packetdrill/files/8847854/artifacts.zip)

**Comment by nealcardwell** [comment]
Sorry I did not see this issue until now. Can you please clarify what the problem is and why you closed this issue? Thanks!
